import { useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ModsList, sortedMods } from "@/components/parts/ModsList";
import { ServiceHistoryList } from "@/components/service/ServiceHistoryList";
import { APP_NAME } from "@/config/env";
import { isBackfilled } from "@/domain/service";
import { formatDate } from "@/domain/time";
import { useBikeService } from "@/hooks/useBikeService";
import { useDb } from "@/hooks/useDb";

/**
 * Printable service history for selling a bike. Light, plain layout so it prints
 * well; "Save as PDF" from the phone's print/share menu gives a file to send.
 */
export default function ServiceHistoryPrint() {
  const { bikeId } = useParams();
  const db = useDb();
  const data = useBikeService(bikeId);
  const [showCost, setShowCost] = useState(false);
  const [showVin, setShowVin] = useState(true);
  if (!data) return <p className="p-6">Bike not found. <Link to="/garage" className="underline">Back to garage</Link></p>;
  const { bike, hours, records, tasks } = data;
  const owner = db.riders[bike.riderId];
  const services = records.filter((r) => r.kind === "service");
  const backfilled = records.filter(isBackfilled).length;

  return (
    <div className="min-h-dvh bg-white text-[#111]">
      <div className="mx-auto max-w-2xl p-5 print:p-0">
        <div className="mb-5 flex flex-wrap items-center gap-2 print:hidden">
          <Link to={`/garage/${bike.id}`} className="inline-flex min-h-12 items-center rounded-xl border border-[#ccc] px-4 font-semibold">← Back</Link>
          <button type="button" onClick={() => window.print()} className="inline-flex min-h-12 items-center rounded-xl bg-[#111] px-4 font-semibold text-white">Print / Save as PDF</button>
          <div className="ml-auto flex flex-wrap gap-x-4">
            <label className="flex min-h-12 items-center gap-2 text-sm"><input type="checkbox" checked={showCost} onChange={(e) => setShowCost(e.target.checked)} className="size-5 accent-[#111]" /> Show costs</label>
            {bike.vin && <label className="flex min-h-12 items-center gap-2 text-sm"><input type="checkbox" checked={showVin} onChange={(e) => setShowVin(e.target.checked)} className="size-5 accent-[#111]" /> Show chassis no.</label>}
          </div>
        </div>

        <header className="border-b-2 border-[#111] pb-3">
          <div className="font-mono text-xs uppercase tracking-[0.14em] text-[#555]">Service history</div>
          <h1 className="font-display text-4xl font-black uppercase leading-none">{[bike.year, bike.manufacturer, bike.model].filter(Boolean).join(" ")}</h1>
          <p className="mt-1 text-sm text-[#555]">{bike.capacity}{owner ? ` · Owner: ${owner.name}` : ""}</p>
          {bike.vin && showVin && <p className="mt-1 text-sm">Chassis no. <span className="font-mono font-bold tracking-wide">{bike.vin}</span> <span className="text-[#555]">(as entered by the owner: check it against the frame)</span></p>}
        </header>

        <dl className="my-4 grid grid-cols-3 gap-3 text-sm">
          <div><dt className="text-[#555]">Engine hours</dt><dd className="font-mono text-2xl font-bold">{hours.total} h</dd></div>
          <div><dt className="text-[#555]">Services logged</dt><dd className="font-mono text-2xl font-bold">{services.length}</dd></div>
          <div><dt className="text-[#555]">Report date</dt><dd className="font-mono text-2xl font-bold">{formatDate(Date.now(), 0)}</dd></div>
        </dl>
        <p className="mb-4 text-sm text-[#333]">
          {hours.meter ? `Hours: last hour-meter reading ${hours.meter.hours} h (${formatDate(hours.meter.performedAt, 0)}) plus ride time recorded in ${APP_NAME} since.` : `Hours: ride time recorded in ${APP_NAME}${bike.startHours ? ` plus ${bike.startHours} h on the bike when added` : ""}.`}
        </p>

        <div className="[&_.text-muted]:text-[#555] [&_li]:border-[#ddd]">
          <ServiceHistoryList bike={bike} records={records} tasks={tasks} showCost={showCost} fullDates />
        </div>

        {sortedMods(bike).length > 0 && (
          <section className="mt-6 break-inside-avoid [&_.text-muted]:text-[#555] [&_li]:border-[#ddd]">
            <h2 className="border-b border-[#111] pb-1 font-mono text-xs font-bold uppercase tracking-[0.14em]">Modifications</h2>
            <ModsList bike={bike} fullDates />
          </section>
        )}

        <footer className="mt-6 border-t border-[#ccc] pt-3 text-xs text-[#555]">
          Generated by {APP_NAME}. Entries are as logged by the owner, each stamped with when it was entered;
          {backfilled ? ` ${backfilled} ${backfilled === 1 ? "entry was" : "entries were"} added more than a week after the work and ${backfilled === 1 ? "is" : "are"} marked “added later”.` : " none were added more than a week after the work."}
          {" "}Ask the seller for receipts to confirm shop work.
        </footer>
      </div>
    </div>
  );
}
